version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-ddbb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=backoffice-backend-dev
    ports:
      - '5432:5432'
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-admin-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adminp@ssw0rd
      - POSTGRES_DB=backoffice-backend-dev
    ports:
      - '5050:80'
    restart: always