version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-ddbb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=backoffice-backend-dev
    ports:
      - '5432:5432'
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-admin-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adminp@ssw0rd
      - POSTGRES_DB=backoffice-backend-dev
    ports:
      - '5050:80'
    restart: always
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq-service
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=p@ssw0rd 
    ports:
      - '5672:5672'
    restart: always
  rabbitmq-management:
    image: rabbitmq:management
    container_name: rabbitmq-management-ui
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=p@ssw0rd 
    ports:
      - '15672:15672'
    restart: always